name: Deploy to Dev

on:
  workflow_run:
    workflows: [CI]
    types:
      - completed
    branches: [dev]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Fetch .env file from server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "/var/www/aihomework/dev/.env"
          target: "."
          strip_components: 4

      - name: Build Docker images
        run: |
          docker compose --env-file .env -f docker-compose.yml build

      - name: List Docker images
        run: docker images

      - name: Save Docker images to tarball
        run: |
          docker save $(docker images --format '{{.Repository}}:{{.Tag}}' | grep -v '<none>') | gzip > dev-images.tar.gz

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: dev-images
          path: dev-images.tar.gz

      - name: Copy Docker images to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "dev-images.tar.gz"
          target: "~/images-tar"

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /var/www/aihomework/dev
            git fetch origin dev
            git stash
            git checkout dev
            git pull
            docker load -i ~/images-tar/dev-images.tar.gz
            docker compose -f docker-compose.yml down
            docker compose -f docker-compose.yml up -d

  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo "CI Workflow failed. Dev deployment was not triggered."